import streamlit as st
import pandas as pd
import plotly.express as px

# =====================================================
# PAGE CONFIG
# =====================================================

st.set_page_config(
    page_title="Financial Impact",
    page_icon="💰",
    layout="wide"
)

st.title("💰 Financial Impact Analysis")
st.caption("Business value generated by the Fraud Detection Model")

# =====================================================
# LOAD DATA
# =====================================================

@st.cache_data
def load_data():
    return pd.read_csv("outputs/business_summary.csv")

business = load_data()

# =====================================================
# KPI CARDS
# =====================================================

st.subheader("📊 Executive Business Summary")

cols = st.columns(len(business))

for i, (_, row) in enumerate(business.iterrows()):
    with cols[i]:
        st.metric(
            row["Metric"],
            row["Value"]
        )

st.divider()

# =====================================================
# BAR CHART
# =====================================================

st.subheader("📈 Financial Metrics")

fig = px.bar(
    business,
    x="Metric",
    y="Value",
    color="Metric",
    text="Value",
    title="Business Summary"
)

fig.update_layout(
    height=500,
    showlegend=False
)

st.plotly_chart(
    fig,
    use_container_width=True
)

st.divider()

# =====================================================
# PIE CHART
# =====================================================

st.subheader("💹 Business Contribution")

pie = px.pie(
    business,
    names="Metric",
    values="Value",
    hole=0.45,
    title="Business Metrics Distribution"
)

pie.update_layout(height=500)

st.plotly_chart(
    pie,
    use_container_width=True
)

st.divider()

# =====================================================
# BUSINESS BENEFITS
# =====================================================

st.subheader("🏦 Business Benefits")

c1, c2 = st.columns(2)

with c1:

    st.success("""

### Operational Benefits

✅ Faster fraud detection

✅ Reduced manual verification

✅ Improved customer trust

✅ Automated transaction monitoring

✅ Scalable fraud detection

""")

with c2:

    st.info("""

### Financial Benefits

💰 Reduced financial losses

💰 Improved fraud prevention

💰 Lower investigation cost

💰 Better operational efficiency

💰 Higher profitability

""")

st.divider()

# =====================================================
# RECOMMENDATIONS
# =====================================================

st.subheader("📋 Recommendations")

st.warning("""

### Recommended Next Steps

1. Deploy the Random Forest model into production.

2. Monitor CASH_OUT and TRANSFER transactions closely.

3. Trigger additional verification for high-value transactions.

4. Retrain the model periodically using new transaction data.

5. Continuously monitor prediction performance.

6. Integrate Explainable AI (SHAP) into production.

""")

st.divider()

# =====================================================
# EXECUTIVE SUMMARY
# =====================================================

st.success("""

## Executive Summary

The Fraud Detection System demonstrates excellent predictive performance while delivering measurable business value.

Key outcomes include:

• High fraud detection accuracy

• Minimal false alarms

• Reduced financial losses

• Improved customer protection

• Better decision making

The Random Forest model is recommended for deployment because it provides the best balance between accuracy, precision, recall and robustness.

""")